### ISSUE TITLE
How much data does this use?

### ISSUE THREAD

**Issue by KTrentLR** [richtr/NoSleep.js#17]
I assume the video that's playing in the background [to keep the browser awake] is of very low quality to keep bandwidth usage low, can you please confirm how much bandwidth is used over the course of 1 minute?  Also, is the video just "black" in that there or no images that might be seen by anyone if someone digs into the data? Lastly, how long is the video?

**Comment by GeertVanWonterghem** [comment]
I'm just a user, not the author of this software. But I think I can answer your questions.

- The video does not use bandwidth, because it is sent along with the code.
- The video is not visible. I don't know what you might find if you dig into the video code. I don't think that could pose a problem.
- I don't know how long the video is, but that does not really matter. I understand it is put in loop, so it keeps playing.

**Comment by KTrentLR** [comment]
Thanks!  that's perfect for my need.
