### ISSUE TITLE
S8+ refreshing

### ISSUE THREAD

**Issue by bobbymale** [richtr/NoSleep.js#38]
It work great for older Android OS and somewhat somehow Google Nougat force refresh in 20 mins. I turn off the battery optimization and keep stay on with no luck and still hard refreshed the page automatically after 20 mins. The same page on older Android works great as well as iOS iPhone6 and iPhone7. Please help with S8+ Samsung Chrome browser.

**Comment by richtr** [comment]
Related to the comment in https://github.com/richtr/NoSleep.js/issues/52#issuecomment-443979974 it seems that usage of this library is not following the guidelines laid out in the  [README](https://github.com/richtr/NoSleep.js/blob/master/README.md):

> // (must be wrapped in a user input event handler e.g. a mouse or touch handler)

This is an acceptable compromise that means you can enable NoSleep if/when the user clicks on your page.

It was never the intention to support non-user-gesture sleep lock and this issue is about auto-enabling wake/sleep lock on this device. Requiring a user gesture to enable sleep lock is an acceptable UX compromise for most experiences.

Closing this issue as this is not an issue with intended usage through a user-initiated gesture.
