### ISSUE TITLE
Let package.json point to /dist file

### ISSUE THREAD

**Issue by ramonavic** [richtr/NoSleep.js#46]
We don't use es6 in our frontend. Therefore our webpack build crashed while trying to build and minify with UglifyJS. This is easily fixed when pointing towards the minified file in your dist folder.

**Comment by nabrown** [comment]
I got this to work with the change that fixed this issue ([commit 48](https://github.com/richtr/NoSleep.js/pull/48/commits/7c3ae7477715aa219336be4b104acacc81230f22)) but I'm just hoping someone has a quick answer to this -- I **am using es6**, with Babel and Webpack, for the front end, so why wouldn't the build work as it was? I'm a Webpack novice so any insight appreciated.
The build command I'm using seems to be `cross-env NODE_ENV=production webpack --progress --hide-modules` (maybe it's that `hide-modules` bit at the end??)

**Comment by alexzaworski** [comment]
@nabrown I'm pretty sure the problem you're having is that babel, by default, does not transpile anything in `node_modules`. So when you're importing `NoSleep` you get the es6 version, and because you're using `NODE_ENV=production` webpack is running it through UglifyJs which barfs when given es6.

If you want a fix without depending on #48 (which unfortunately is in PR limbo it seems) you can do this:

```
import NoSleep from 'nosleep.js/dist/NoSleep.js'
```
