### ISSUE TITLE
Very high CPU usage on desktop Chrome and Brave browsers

### ISSUE THREAD

**Issue by pmiklos** [richtr/NoSleep.js#66]
* Device Name: Ubuntu Linux (Dell XPS 13,  Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz)
* Device Version: Ubuntu 16.04.5 LTS ( 4.15.0-42-generic #45~16.04.1-Ubuntu SMP Mon Nov 19 13:02:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
* Browser Name: Chrome / Brave
* Browser Version: Chrome 72.0.3626.81 (Official Build) (64-bit) / Brave 0.58.21 Chromium: 71.0.3578.98 (Official Build)
* NoSleep.js Version: 0.9.0

### Expected Behavior

Do not use excessive CPU

### Actual Behavior

The CPU usage goes up to 170-180% (inspecting in Chrome task manager) as soon as the NoSleep enable() function is called and my laptop starts overheating.

I doesn't seem to happen with Firefox and I also tested on Android 9 (Pixel 3) which didn't seem to overheat or use much cpu. 

I understand that the primary target of this library is mobile devices, but it still shouldn't behave as described above on desktop.

### Code

I used the live example page 

### How Do We Reproduce?

Go to the live demo page and enable wake lock, press Shift+Esc and see the CPU usage shooting up.

**Comment by pmiklos** [comment]
It has something to do with the webm file. If I disable that from the video sources, mp4 starts playing and that one uses significantly less cpu (jumping around 10%-20%) .
I wonder why the mp4 is implemented in way to constantly update the video position rather than looping. Looping seems to use less resources.

**Comment by pmiklos** [comment]
generated a new webm video as below that consumes only 1-3% CPU. It's slightly bigger in size though:

     ffmpeg -r 20 -t 1 -s 1x1 -f rawvideo -pix_fmt rgb24 -i /dev/zero noop.mpeg
     ffmpeg -i noop.mpeg -c:v libvpx -an noop.webm

**Comment by pmiklos** [comment]
found a better way, generate a  5sec 1fps webm which doesn't even spike the CPU:

    ffmpeg -r 20 -t 4 -s 1x1 -f rawvideo -pix_fmt rgb24 -i /dev/zero noop.mpeg
    ffmpeg -i noop.mpeg -c:v libvpx -an -r 1 noop.webm

The only thing is that the code has to be changed to check the currently playing source when testing for the media to loop

    if (this.noSleepVideo.currentSrc.includes('video/webm')) {
         this.noSleepVideo.setAttribute('loop', '')
    }

**Comment by LeandroJF** [comment]
Hey, can you post here the new generated video files? You can use this tool to convert them to data URI:
https://dopiaza.org/tools/datauri/index.php

Tks in advance

**Comment by pmiklos** [comment]
You can't find it here. It required another change in index.js to detect the video (since it's not 1sec anymore). Also I only tested it with Brave and Chrome browsers on desktop and with Android Brave on Pixel 3.

https://github.com/pmiklos/NoSleep.js/commit/963a9e8b2e537cb7bedcd41a2ff29fc1a754856e

**Comment by LeandroJF** [comment]
Ok, tks

**Comment by ViRPo** [comment]
I created a pull request that will hopefully fix these CPU issues:
https://github.com/richtr/NoSleep.js/pull/65

**Comment by viktorvi** [comment]
I have same problem with Chrome.

**Comment by pedromarquesm** [comment]
just found out this is the problem for my computer to always having it's fans at max.
CPU usage from Chrome task manager pointed out 170
After disabling NoSleep, way below 20...
any fix by now?

**Comment by hugovk** [comment]
@pedromarquesm Use NoSleep.js from https://github.com/richtr/NoSleep.js/pull/65.

**Comment by pedromarquesm** [comment]
last commit on 5 december of 2018. is this repo already dead?
There are improvements not being accepted...

**Comment by garygrubb** [comment]
> found a better way, generate a 5sec 1fps webm which doesn't even spike the CPU:
> 
> ```
> ffmpeg -r 20 -t 4 -s 1x1 -f rawvideo -pix_fmt rgb24 -i /dev/zero noop.mpeg
> ffmpeg -i noop.mpeg -c:v libvpx -an -r 1 noop.webm
> ```
> The only thing is that the code has to be changed to check the currently playing source when testing for the media to loop
> 
> ```
> if (this.noSleepVideo.currentSrc.includes('video/webm')) {
>      this.noSleepVideo.setAttribute('loop', '')
> }
> ```

Thank you. This really makes a difference. It reduced by CPU utilisation from 50% to almost idle.

**Comment by a22aaass** [comment]
> > found a better way, generate a 5sec 1fps webm which doesn't even spike the CPU:
> > ```
> > ffmpeg -r 20 -t 4 -s 1x1 -f rawvideo -pix_fmt rgb24 -i /dev/zero noop.mpeg
> > ffmpeg -i noop.mpeg -c:v libvpx -an -r 1 noop.webm
> > ```
> > The only thing is that the code has to be changed to check the currently playing source when testing for the media to loop
> > ```
> > if (this.noSleepVideo.currentSrc.includes('video/webm')) {
> >      this.noSleepVideo.setAttribute('loop', '')
> > }
> > ```
> 
> Thank you. This really makes a difference. It reduced by CPU utilisation from 50% to almost idle.

how can i use it? 
"ffmpeg -r 20 -t 4 -s 1x1 -f rawvideo -pix_fmt rgb24 -i /dev/zero noop.mpeg
ffmpeg -i noop.mpeg -c:v libvpx -an -r 1 noop.webm"

**Comment by garygrubb** [comment]
> > > found a better way, generate a 5sec 1fps webm which doesn't even spike the CPU:
> > > ```
> > > ffmpeg -r 20 -t 4 -s 1x1 -f rawvideo -pix_fmt rgb24 -i /dev/zero noop.mpeg
> > > ffmpeg -i noop.mpeg -c:v libvpx -an -r 1 noop.webm
> > > ```
> > > The only thing is that the code has to be changed to check the currently playing source when testing for the media to loop
> > > ```
> > > if (this.noSleepVideo.currentSrc.includes('video/webm')) {
> > >      this.noSleepVideo.setAttribute('loop', '')
> > > }
> > > ```
> > 
> > 
> > Thank you. This really makes a difference. It reduced by CPU utilisation from 50% to almost idle.
> 
> how can i use it?
> "ffmpeg -r 20 -t 4 -s 1x1 -f rawvideo -pix_fmt rgb24 -i /dev/zero noop.mpeg
> ffmpeg -i noop.mpeg -c:v libvpx -an -r 1 noop.webm"

You need to run the ffmpeg commands on a Linux machine where the tool is available to generate the template video files. Use thee videos in NoSleep.js instead of importing the strings which are present by default.

This is my code in a react project.

`// const webm= 'data:video/webm;base64,GkXfo0AgQoaBAUL3gQFC8oEEQvOBCEKCQAR3ZWJtQoeBAkKFgQIYU4BnQI0VSalmQCgq17FAAw9CQE2AQAZ3aGFtbXlXQUAGd2hhbW15RIlACECPQAAAAAAAFlSua0AxrkAu14EBY8WBAZyBACK1nEADdW5khkAFVl9WUDglhohAA1ZQOIOBAeBABrCBCLqBCB9DtnVAIueBAKNAHIEAAIAwAQCdASoIAAgAAUAmJaQAA3AA/vz0AAA=';
// const mp4= 'data:video/mp4;base64,AAAAIGZ0eXBtcDQyAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAACKBtZGF0AAAC8wYF///v3EXpvebZSLeWLNgg2SPu73gyNjQgLSBjb3JlIDE0MiByMjQ3OSBkZDc5YTYxIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAxNCAtIGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTEgZGVibG9jaz0xOjA6MCBhbmFseXNlPTB4MToweDExMSBtZT1oZXggc3VibWU9MiBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0wIG1lX3JhbmdlPTE2IGNocm9tYV9tZT0xIHRyZWxsaXM9MCA4eDhkY3Q9MCBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hyb21hX3FwX29mZnNldD0wIHRocmVhZHM9NiBsb29rYWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0xIGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTMgYl9weXJhbWlkPTIgYl9hZGFwdD0xIGJfYmlhcz0wIGRpcmVjdD0xIHdlaWdodGI9MSBvcGVuX2dvcD0wIHdlaWdodHA9MSBrZXlpbnQ9MzAwIGtleWludF9taW49MzAgc2NlbmVjdXQ9NDAgaW50cmFfcmVmcmVzaD0wIHJjX2xvb2thaGVhZD0xMCByYz1jcmYgbWJ0cmVlPTEgY3JmPTIwLjAgcWNvbXA9MC42MCBxcG1pbj0wIHFwbWF4PTY5IHFwc3RlcD00IHZidl9tYXhyYXRlPTIwMDAwIHZidl9idWZzaXplPTI1MDAwIGNyZl9tYXg9MC4wIG5hbF9ocmQ9bm9uZSBmaWxsZXI9MCBpcF9yYXRpbz0xLjQwIGFxPTE6MS4wMACAAAAAOWWIhAA3//p+C7v8tDDSTjf97w55i3SbRPO4ZY+hkjD5hbkAkL3zpJ6h/LR1CAABzgB1kqqzUorlhQAAAAxBmiQYhn/+qZYADLgAAAAJQZ5CQhX/AAj5IQADQGgcIQADQGgcAAAACQGeYUQn/wALKCEAA0BoHAAAAAkBnmNEJ/8ACykhAANAaBwhAANAaBwAAAANQZpoNExDP/6plgAMuSEAA0BoHAAAAAtBnoZFESwr/wAI+SEAA0BoHCEAA0BoHAAAAAkBnqVEJ/8ACykhAANAaBwAAAAJAZ6nRCf/AAsoIQADQGgcIQADQGgcAAAADUGarDRMQz/+qZYADLghAANAaBwAAAALQZ7KRRUsK/8ACPkhAANAaBwAAAAJAZ7pRCf/AAsoIQADQGgcIQADQGgcAAAACQGe60Qn/wALKCEAA0BoHAAAAA1BmvA0TEM//qmWAAy5IQADQGgcIQADQGgcAAAAC0GfDkUVLCv/AAj5IQADQGgcAAAACQGfLUQn/wALKSEAA0BoHCEAA0BoHAAAAAkBny9EJ/8ACyghAANAaBwAAAANQZs0NExDP/6plgAMuCEAA0BoHAAAAAtBn1JFFSwr/wAI+SEAA0BoHCEAA0BoHAAAAAkBn3FEJ/8ACyghAANAaBwAAAAJAZ9zRCf/AAsoIQADQGgcIQADQGgcAAAADUGbeDRMQz/+qZYADLkhAANAaBwAAAALQZ+WRRUsK/8ACPghAANAaBwhAANAaBwAAAAJAZ+1RCf/AAspIQADQGgcAAAACQGft0Qn/wALKSEAA0BoHCEAA0BoHAAAAA1Bm7w0TEM//qmWAAy4IQADQGgcAAAAC0Gf2kUVLCv/AAj5IQADQGgcAAAACQGf+UQn/wALKCEAA0BoHCEAA0BoHAAAAAkBn/tEJ/8ACykhAANAaBwAAAANQZvgNExDP/6plgAMuSEAA0BoHCEAA0BoHAAAAAtBnh5FFSwr/wAI+CEAA0BoHAAAAAkBnj1EJ/8ACyghAANAaBwhAANAaBwAAAAJAZ4/RCf/AAspIQADQGgcAAAADUGaJDRMQz/+qZYADLghAANAaBwAAAALQZ5CRRUsK/8ACPkhAANAaBwhAANAaBwAAAAJAZ5hRCf/AAsoIQADQGgcAAAACQGeY0Qn/wALKSEAA0BoHCEAA0BoHAAAAA1Bmmg0TEM//qmWAAy5IQADQGgcAAAAC0GehkUVLCv/AAj5IQADQGgcIQADQGgcAAAACQGepUQn/wALKSEAA0BoHAAAAAkBnqdEJ/8ACyghAANAaBwAAAANQZqsNExDP/6plgAMuCEAA0BoHCEAA0BoHAAAAAtBnspFFSwr/wAI+SEAA0BoHAAAAAkBnulEJ/8ACyghAANAaBwhAANAaBwAAAAJAZ7rRCf/AAsoIQADQGgcAAAADUGa8DRMQz/+qZYADLkhAANAaBwhAANAaBwAAAALQZ8ORRUsK/8ACPkhAANAaBwAAAAJAZ8tRCf/AAspIQADQGgcIQADQGgcAAAACQGfL0Qn/wALKCEAA0BoHAAAAA1BmzQ0TEM//qmWAAy4IQADQGgcAAAAC0GfUkUVLCv/AAj5IQADQGgcIQADQGgcAAAACQGfcUQn/wALKCEAA0BoHAAAAAkBn3NEJ/8ACyghAANAaBwhAANAaBwAAAANQZt4NExC//6plgAMuSEAA0BoHAAAAAtBn5ZFFSwr/wAI+CEAA0BoHCEAA0BoHAAAAAkBn7VEJ/8ACykhAANAaBwAAAAJAZ+3RCf/AAspIQADQGgcAAAADUGbuzRMQn/+nhAAYsAhAANAaBwhAANAaBwAAAAJQZ/aQhP/AAspIQADQGgcAAAACQGf+UQn/wALKCEAA0BoHCEAA0BoHCEAA0BoHCEAA0BoHCEAA0BoHCEAA0BoHAAACiFtb292AAAAbG12aGQAAAAA1YCCX9WAgl8AAAPoAAAH/AABAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAGGlvZHMAAAAAEICAgAcAT////v7/AAAF+XRyYWsAAABcdGtoZAAAAAPVgIJf1YCCXwAAAAEAAAAAAAAH0AAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAygAAAMoAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAB9AAABdwAAEAAAAABXFtZGlhAAAAIG1kaGQAAAAA1YCCX9WAgl8AAV+QAAK/IFXEAAAAAAAtaGRscgAAAAAAAAAAdmlkZQAAAAAAAAAAAAAAAFZpZGVvSGFuZGxlcgAAAAUcbWluZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAAE3HN0YmwAAACYc3RzZAAAAAAAAAABAAAAiGF2YzEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAygDKAEgAAABIAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY//8AAAAyYXZjQwFNQCj/4QAbZ01AKOyho3ySTUBAQFAAAAMAEAAr8gDxgxlgAQAEaO+G8gAAABhzdHRzAAAAAAAAAAEAAAA8AAALuAAAABRzdHNzAAAAAAAAAAEAAAABAAAB8GN0dHMAAAAAAAAAPAAAAAEAABdwAAAAAQAAOpgAAAABAAAXcAAAAAEAAAAAAAAAAQAAC7gAAAABAAA6mAAAAAEAABdwAAAAAQAAAAAAAAABAAALuAAAAAEAADqYAAAAAQAAF3AAAAABAAAAAAAAAAEAAAu4AAAAAQAAOpgAAAABAAAXcAAAAAEAAAAAAAAAAQAAC7gAAAABAAA6mAAAAAEAABdwAAAAAQAAAAAAAAABAAALuAAAAAEAADqYAAAAAQAAF3AAAAABAAAAAAAAAAEAAAu4AAAAAQAAOpgAAAABAAAXcAAAAAEAAAAAAAAAAQAAC7gAAAABAAA6mAAAAAEAABdwAAAAAQAAAAAAAAABAAALuAAAAAEAADqYAAAAAQAAF3AAAAABAAAAAAAAAAEAAAu4AAAAAQAAOpgAAAABAAAXcAAAAAEAAAAAAAAAAQAAC7gAAAABAAA6mAAAAAEAABdwAAAAAQAAAAAAAAABAAALuAAAAAEAADqYAAAAAQAAF3AAAAABAAAAAAAAAAEAAAu4AAAAAQAAOpgAAAABAAAXcAAAAAEAAAAAAAAAAQAAC7gAAAABAAA6mAAAAAEAABdwAAAAAQAAAAAAAAABAAALuAAAAAEAAC7gAAAAAQAAF3AAAAABAAAAAAAAABxzdHNjAAAAAAAAAAEAAAABAAAAAQAAAAEAAAEEc3RzegAAAAAAAAAAAAAAPAAAAzQAAAAQAAAADQAAAA0AAAANAAAAEQAAAA8AAAANAAAADQAAABEAAAAPAAAADQAAAA0AAAARAAAADwAAAA0AAAANAAAAEQAAAA8AAAANAAAADQAAABEAAAAPAAAADQAAAA0AAAARAAAADwAAAA0AAAANAAAAEQAAAA8AAAANAAAADQAAABEAAAAPAAAADQAAAA0AAAARAAAADwAAAA0AAAANAAAAEQAAAA8AAAANAAAADQAAABEAAAAPAAAADQAAAA0AAAARAAAADwAAAA0AAAANAAAAEQAAAA8AAAANAAAADQAAABEAAAANAAAADQAAAQBzdGNvAAAAAAAAADwAAAAwAAADZAAAA3QAAAONAAADoAAAA7kAAAPQAAAD6wAAA/4AAAQXAAAELgAABEMAAARcAAAEbwAABIwAAAShAAAEugAABM0AAATkAAAE/wAABRIAAAUrAAAFQgAABV0AAAVwAAAFiQAABaAAAAW1AAAFzgAABeEAAAX+AAAGEwAABiwAAAY/AAAGVgAABnEAAAaEAAAGnQAABrQAAAbPAAAG4gAABvUAAAcSAAAHJwAAB0AAAAdTAAAHcAAAB4UAAAeeAAAHsQAAB8gAAAfjAAAH9gAACA8AAAgmAAAIQQAACFQAAAhnAAAIhAAACJcAAAMsdHJhawAAAFx0a2hkAAAAA9WAgl/VgIJfAAAAAgAAAAAAAAf8AAAAAAAAAAAAAAABAQAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAACsm1kaWEAAAAgbWRoZAAAAADVgIJf1YCCXwAArEQAAWAAVcQAAAAAACdoZGxyAAAAAAAAAABzb3VuAAAAAAAAAAAAAAAAU3RlcmVvAAAAAmNtaW5mAAAAEHNtaGQAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAidzdGJsAAAAZ3N0c2QAAAAAAAAAAQAAAFdtcDRhAAAAAAAAAAEAAAAAAAAAAAACABAAAAAArEQAAAAAADNlc2RzAAAAAAOAgIAiAAIABICAgBRAFQAAAAADDUAAAAAABYCAgAISEAaAgIABAgAAABhzdHRzAAAAAAAAAAEAAABYAAAEAAAAABxzdHNjAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAUc3RzegAAAAAAAAAGAAAAWAAAAXBzdGNvAAAAAAAAAFgAAAOBAAADhwAAA5oAAAOtAAADswAAA8oAAAPfAAAD5QAAA/gAAAQLAAAEEQAABCgAAAQ9AAAEUAAABFYAAARpAAAEgAAABIYAAASbAAAErgAABLQAAATHAAAE3gAABPMAAAT5AAAFDAAABR8AAAUlAAAFPAAABVEAAAVXAAAFagAABX0AAAWDAAAFmgAABa8AAAXCAAAFyAAABdsAAAXyAAAF+AAABg0AAAYgAAAGJgAABjkAAAZQAAAGZQAABmsAAAZ+AAAGkQAABpcAAAauAAAGwwAABskAAAbcAAAG7wAABwYAAAcMAAAHIQAABzQAAAc6AAAHTQAAB2QAAAdqAAAHfwAAB5IAAAeYAAAHqwAAB8IAAAfXAAAH3QAAB/AAAAgDAAAICQAACCAAAAg1AAAIOwAACE4AAAhhAAAIeAAACH4AAAiRAAAIpAAACKoAAAiwAAAItgAACLwAAAjCAAAAFnVkdGEAAAAObmFtZVN0ZXJlbwAAAHB1ZHRhAAAAaG1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAAO2lsc3QAAAAzqXRvbwAAACtkYXRhAAAAAQAAAABIYW5kQnJha2UgMC4xMC4yIDIwMTUwNjExMDA=';

import webm from './webm.webm'
import mp4 from './mp4.mpeg'`


Also don't forget to update the id statement as described in previous post.

**Comment by a22aaass** [comment]
> > > > found a better way, generate a 5sec 1fps webm which doesn't even spike the CPU:
> > > > ```
> > > > ffmpeg -r 20 -t 4 -s 1x1 -f rawvideo -pix_fmt rgb24 -i /dev/zero noop.mpeg
> > > > ffmpeg -i noop.mpeg -c:v libvpx -an -r 1 noop.webm
> > > > ```
> > > > The only thing is that the code has to be changed to check the currently playing source when testing for the media to loop
> > > > ```
> > > > if (this.noSleepVideo.currentSrc.includes('video/webm')) {
> > > >      this.noSleepVideo.setAttribute('loop', '')
> > > > }
> > > > ```
> > > 
> > > 
> > > Thank you. This really makes a difference. It reduced by CPU utilisation from 50% to almost idle.
> > 
> > 
> > how can i use it?
> > "ffmpeg -r 20 -t 4 -s 1x1 -f rawvideo -pix_fmt rgb24 -i /dev/zero noop.mpeg
> > ffmpeg -i noop.mpeg -c:v libvpx -an -r 1 noop.webm"
> 
> You need to run the ffmpeg commands on a Linux machine where the tool is available to generate the template video files. Use thee videos in NoSleep.js instead of importing the strings which are present by default.
> 
> This is my code in a react project.
> 
> ```
> // const webm= 'data:video/webm;base64,G...3AA/vz0AAA=';
> // const mp4= 'data:video/mp4;base64,AAAAIG...DA=';
> 
> import webm from './webm.webm'
> import mp4 from './mp4.mpeg'
> ```
> Also don't forget to update the if statement as described in previous post.

yep,i get it 
tks!!!!  I hope we shall be good friends

**Comment by timtribers** [comment]
Can't wait to use the latest version of this lib (thx for all the hard work recently @richtr), but unfortunately I'm stuck on v0.8 - if I move to any later release I get this problem of maxed out CPU in Chrome (on Windows).  I take it that the video file changed after that release.  Does it need something like PR#65 to fix this? (Will post this there too)

**Comment by mhmo91** [comment]
> Man, I thought I was going crazy. I've been trying to profile my reactjs app trying to find the problem. I didn't think it would be caused by this lib.

Same here! 
there should be a Warning somewhere in the library readMe. i wasted sooooo many hours because of this!!!

**Comment by richtr** [comment]
The video files suggested in #65 have now been merged to `master` (via 2ebb9011f7849d033e0c9250e49b9e2f09dc6bf6).

This should reduce CPU usage based on the discussions from #65.

I will release a new version of this library shortly with these fixes included.

**Comment by MasterInQuestion** [comment]
[ Quote pmiklos @ CE 2019-02-07 05:55:53 UTC:
[https://github<i>.</i>com/richtr/NoSleep.js/issues/66#issuecomment-461297387](https://github.com/richtr/NoSleep.js/issues/66#issuecomment-461297387)
    I wonder why the mp4 is implemented in way to constantly update the video position rather than looping. Looping seems to use less resources. ]
<^>    Related commits:
    [https://github<i>.</i>com/richtr/NoSleep.js/pull/32/files#diff-89779e3bb9293db4f0888f94691e5e313edfe27a2a234cf037e866f9f197abc8R27-R31](https://github.com/richtr/NoSleep.js/pull/32/files#diff-89779e3bb9293db4f0888f94691e5e313edfe27a2a234cf037e866f9f197abc8R27-R31)
    [https://github<i>.</i>com/richtr/NoSleep.js/commit/016580ddd200ff6e7a12f0904c314e3ee2c9bae1#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R25 ](https://github.com/richtr/NoSleep.js/commit/016580ddd200ff6e7a12f0904c314e3ee2c9bae1#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R25)

    Also note: theoretically updating the playback position (when done properly) should cause less load than looping the whole video.
    NoSleep.js failed to do so by listening on the wrong event ("timeupdate") and doing pointless operations (&#x60;if ( currentTime > 0.5 )&#x60; and &#x60;Math.random()&#x60;).

**Comment by a22aaass** [comment]
什么事吖

**Comment by MasterInQuestion** [comment]
@a22aaass,
    Initially I thought your reply was an AI generated test [1], my apologies.
    After more careful checking I noted your reply might be of actual meaning.
    .
    So I would like to inform you that I'm recently analyzing the optimal way to implement the WakeLock.
    For more details, check the linked posts. (or my recent activities)

[1] Due to the extremely close timestamp to my post, and some low-effort background research that happened to have failed.
